# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\CarCheck\ui\widgets\edit_item.ui'
#
# Created: Fri Mar 30 17:00:54 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Edit_Item_ui(object):
    def setupUi(self, Edit_Item_ui):
        Edit_Item_ui.setObjectName("Edit_Item_ui")
        Edit_Item_ui.resize(255, 433)
        self.formLayout = QtGui.QFormLayout(Edit_Item_ui)
        self.formLayout.setObjectName("formLayout")
        self.line_owner = QtGui.QLineEdit(Edit_Item_ui)
        self.line_owner.setObjectName("line_owner")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.line_owner)
        self.line_client = QtGui.QLineEdit(Edit_Item_ui)
        self.line_client.setObjectName("line_client")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.line_client)
        self.label_client = QtGui.QLabel(Edit_Item_ui)
        self.label_client.setObjectName("label_client")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_client)
        self.label_owner = QtGui.QLabel(Edit_Item_ui)
        self.label_owner.setObjectName("label_owner")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_owner)
        self.label_car_number = QtGui.QLabel(Edit_Item_ui)
        self.label_car_number.setObjectName("label_car_number")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_car_number)
        self.line_car_number = QtGui.QLineEdit(Edit_Item_ui)
        self.line_car_number.setObjectName("line_car_number")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.line_car_number)
        self.label_zone = QtGui.QLabel(Edit_Item_ui)
        self.label_zone.setObjectName("label_zone")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_zone)
        self.line_zone = QtGui.QLineEdit(Edit_Item_ui)
        self.line_zone.setObjectName("line_zone")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.line_zone)
        self.label_status = QtGui.QLabel(Edit_Item_ui)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_status)
        self.line_status = QtGui.QLineEdit(Edit_Item_ui)
        self.line_status.setObjectName("line_status")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.line_status)
        self.date_start = QtGui.QDateEdit(Edit_Item_ui)
        self.date_start.setCalendarPopup(True)
        self.date_start.setObjectName("date_start")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.date_start)
        self.date_end = QtGui.QDateEdit(Edit_Item_ui)
        self.date_end.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.date_end.setCalendarPopup(True)
        self.date_end.setObjectName("date_end")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.date_end)
        self.label_date_start = QtGui.QLabel(Edit_Item_ui)
        self.label_date_start.setObjectName("label_date_start")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_date_start)
        self.label_date_end = QtGui.QLabel(Edit_Item_ui)
        self.label_date_end.setObjectName("label_date_end")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_date_end)
        self.line_price = QtGui.QLineEdit(Edit_Item_ui)
        self.line_price.setObjectName("line_price")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.line_price)
        self.line_payment = QtGui.QLineEdit(Edit_Item_ui)
        self.line_payment.setObjectName("line_payment")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.line_payment)
        self.plain_description = QtGui.QPlainTextEdit(Edit_Item_ui)
        self.plain_description.setObjectName("plain_description")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.plain_description)
        self.label_price = QtGui.QLabel(Edit_Item_ui)
        self.label_price.setObjectName("label_price")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_price)
        self.label_payment = QtGui.QLabel(Edit_Item_ui)
        self.label_payment.setObjectName("label_payment")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_payment)
        self.label_description = QtGui.QLabel(Edit_Item_ui)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_description)
        self.buttonBox = QtGui.QDialogButtonBox(Edit_Item_ui)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.check_hidden = QtGui.QCheckBox(Edit_Item_ui)
        self.check_hidden.setObjectName("check_hidden")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.check_hidden)
        self.check_silenced = QtGui.QCheckBox(Edit_Item_ui)
        self.check_silenced.setObjectName("check_silenced")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.check_silenced)
        self.line_sts = QtGui.QLineEdit(Edit_Item_ui)
        self.line_sts.setObjectName("line_sts")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.line_sts)
        self.label_sts = QtGui.QLabel(Edit_Item_ui)
        self.label_sts.setObjectName("label_sts")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_sts)
        self.label_eco = QtGui.QLabel(Edit_Item_ui)
        self.label_eco.setObjectName("label_eco")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_eco)
        self.line_eco = QtGui.QLineEdit(Edit_Item_ui)
        self.line_eco.setObjectName("line_eco")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.line_eco)

        self.retranslateUi(Edit_Item_ui)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Edit_Item_ui.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Edit_Item_ui.reject)
        QtCore.QMetaObject.connectSlotsByName(Edit_Item_ui)
        Edit_Item_ui.setTabOrder(self.line_car_number, self.line_client)
        Edit_Item_ui.setTabOrder(self.line_client, self.line_owner)
        Edit_Item_ui.setTabOrder(self.line_owner, self.line_zone)
        Edit_Item_ui.setTabOrder(self.line_zone, self.line_status)
        Edit_Item_ui.setTabOrder(self.line_status, self.date_start)
        Edit_Item_ui.setTabOrder(self.date_start, self.date_end)
        Edit_Item_ui.setTabOrder(self.date_end, self.line_price)
        Edit_Item_ui.setTabOrder(self.line_price, self.line_payment)
        Edit_Item_ui.setTabOrder(self.line_payment, self.plain_description)
        Edit_Item_ui.setTabOrder(self.plain_description, self.buttonBox)
        Edit_Item_ui.setTabOrder(self.buttonBox, self.check_hidden)
        Edit_Item_ui.setTabOrder(self.check_hidden, self.check_silenced)

    def retranslateUi(self, Edit_Item_ui):
        Edit_Item_ui.setWindowTitle(QtGui.QApplication.translate("Edit_Item_ui", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_client.setText(QtGui.QApplication.translate("Edit_Item_ui", "Заказчик", None, QtGui.QApplication.UnicodeUTF8))
        self.label_owner.setText(QtGui.QApplication.translate("Edit_Item_ui", "Владелец", None, QtGui.QApplication.UnicodeUTF8))
        self.label_car_number.setText(QtGui.QApplication.translate("Edit_Item_ui", "РегЗнак", None, QtGui.QApplication.UnicodeUTF8))
        self.label_zone.setText(QtGui.QApplication.translate("Edit_Item_ui", "Зона действия", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("Edit_Item_ui", "Статус", None, QtGui.QApplication.UnicodeUTF8))
        self.date_start.setDisplayFormat(QtGui.QApplication.translate("Edit_Item_ui", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_end.setDisplayFormat(QtGui.QApplication.translate("Edit_Item_ui", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_date_start.setText(QtGui.QApplication.translate("Edit_Item_ui", "Дата начала", None, QtGui.QApplication.UnicodeUTF8))
        self.label_date_end.setText(QtGui.QApplication.translate("Edit_Item_ui", "Дата конца", None, QtGui.QApplication.UnicodeUTF8))
        self.label_price.setText(QtGui.QApplication.translate("Edit_Item_ui", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.label_payment.setText(QtGui.QApplication.translate("Edit_Item_ui", "Оплата", None, QtGui.QApplication.UnicodeUTF8))
        self.label_description.setText(QtGui.QApplication.translate("Edit_Item_ui", "Примечания", None, QtGui.QApplication.UnicodeUTF8))
        self.check_hidden.setText(QtGui.QApplication.translate("Edit_Item_ui", "Скрытый", None, QtGui.QApplication.UnicodeUTF8))
        self.check_silenced.setText(QtGui.QApplication.translate("Edit_Item_ui", "Напоминание", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sts.setText(QtGui.QApplication.translate("Edit_Item_ui", "СТС", None, QtGui.QApplication.UnicodeUTF8))
        self.label_eco.setText(QtGui.QApplication.translate("Edit_Item_ui", "Эко-класс", None, QtGui.QApplication.UnicodeUTF8))

