# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Python\CarCheck\ui\widgets\edit_item.ui'
#
# Created: Fri May 18 11:52:01 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Edit_Item_ui(object):
    def setupUi(self, Edit_Item_ui):
        Edit_Item_ui.setObjectName("Edit_Item_ui")
        Edit_Item_ui.resize(255, 459)
        self.formLayout = QtGui.QFormLayout(Edit_Item_ui)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_client = QtGui.QLabel(Edit_Item_ui)
        self.label_client.setObjectName("label_client")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_client)
        self.line_client = QtGui.QLineEdit(Edit_Item_ui)
        self.line_client.setObjectName("line_client")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.line_client)
        self.label_owner = QtGui.QLabel(Edit_Item_ui)
        self.label_owner.setObjectName("label_owner")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_owner)
        self.line_owner = QtGui.QLineEdit(Edit_Item_ui)
        self.line_owner.setObjectName("line_owner")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.line_owner)
        self.label_car_number = QtGui.QLabel(Edit_Item_ui)
        self.label_car_number.setObjectName("label_car_number")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_car_number)
        self.line_car_number = QtGui.QLineEdit(Edit_Item_ui)
        self.line_car_number.setObjectName("line_car_number")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.line_car_number)
        self.label_sts = QtGui.QLabel(Edit_Item_ui)
        self.label_sts.setObjectName("label_sts")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_sts)
        self.line_sts = QtGui.QLineEdit(Edit_Item_ui)
        self.line_sts.setObjectName("line_sts")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.line_sts)
        self.label_zone = QtGui.QLabel(Edit_Item_ui)
        self.label_zone.setObjectName("label_zone")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_zone)
        self.box_zone = QtGui.QComboBox(Edit_Item_ui)
        self.box_zone.setObjectName("box_zone")
        self.box_zone.addItem("")
        self.box_zone.addItem("")
        self.box_zone.addItem("")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.box_zone)
        self.label_status = QtGui.QLabel(Edit_Item_ui)
        self.label_status.setObjectName("label_status")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_status)
        self.box_status = QtGui.QComboBox(Edit_Item_ui)
        self.box_status.setObjectName("box_status")
        self.box_status.addItem("")
        self.box_status.addItem("")
        self.box_status.addItem("")
        self.box_status.addItem("")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.box_status)
        self.label_eco = QtGui.QLabel(Edit_Item_ui)
        self.label_eco.setObjectName("label_eco")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_eco)
        self.box_eco = QtGui.QComboBox(Edit_Item_ui)
        self.box_eco.setObjectName("box_eco")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.box_eco.addItem("")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.box_eco)
        self.label_date_start = QtGui.QLabel(Edit_Item_ui)
        self.label_date_start.setObjectName("label_date_start")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_date_start)
        self.date_start = QtGui.QDateEdit(Edit_Item_ui)
        self.date_start.setCalendarPopup(True)
        self.date_start.setObjectName("date_start")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.date_start)
        self.date_end = QtGui.QDateEdit(Edit_Item_ui)
        self.date_end.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.date_end.setCalendarPopup(True)
        self.date_end.setObjectName("date_end")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.date_end)
        self.label_price = QtGui.QLabel(Edit_Item_ui)
        self.label_price.setObjectName("label_price")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_price)
        self.line_price = QtGui.QLineEdit(Edit_Item_ui)
        self.line_price.setObjectName("line_price")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.line_price)
        self.label_payment = QtGui.QLabel(Edit_Item_ui)
        self.label_payment.setObjectName("label_payment")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.label_payment)
        self.line_payment = QtGui.QLineEdit(Edit_Item_ui)
        self.line_payment.setObjectName("line_payment")
        self.formLayout.setWidget(12, QtGui.QFormLayout.FieldRole, self.line_payment)
        self.label_description = QtGui.QLabel(Edit_Item_ui)
        self.label_description.setObjectName("label_description")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.label_description)
        self.plain_description = QtGui.QPlainTextEdit(Edit_Item_ui)
        self.plain_description.setObjectName("plain_description")
        self.formLayout.setWidget(13, QtGui.QFormLayout.FieldRole, self.plain_description)
        self.check_hidden = QtGui.QCheckBox(Edit_Item_ui)
        self.check_hidden.setObjectName("check_hidden")
        self.formLayout.setWidget(14, QtGui.QFormLayout.LabelRole, self.check_hidden)
        self.check_silenced = QtGui.QCheckBox(Edit_Item_ui)
        self.check_silenced.setObjectName("check_silenced")
        self.formLayout.setWidget(14, QtGui.QFormLayout.FieldRole, self.check_silenced)
        self.buttonBox = QtGui.QDialogButtonBox(Edit_Item_ui)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(15, QtGui.QFormLayout.SpanningRole, self.buttonBox)
        self.label_date_end = QtGui.QLabel(Edit_Item_ui)
        self.label_date_end.setObjectName("label_date_end")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_date_end)
        self.label_date_docs = QtGui.QLabel(Edit_Item_ui)
        self.label_date_docs.setObjectName("label_date_docs")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_date_docs)
        self.date_docs = QtGui.QDateEdit(Edit_Item_ui)
        self.date_docs.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.date_docs.setCalendarPopup(True)
        self.date_docs.setObjectName("date_docs")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.date_docs)

        self.retranslateUi(Edit_Item_ui)
        QtCore.QMetaObject.connectSlotsByName(Edit_Item_ui)
        Edit_Item_ui.setTabOrder(self.line_client, self.line_owner)
        Edit_Item_ui.setTabOrder(self.line_owner, self.line_sts)
        Edit_Item_ui.setTabOrder(self.line_sts, self.line_price)
        Edit_Item_ui.setTabOrder(self.line_price, self.line_payment)
        Edit_Item_ui.setTabOrder(self.line_payment, self.date_start)
        Edit_Item_ui.setTabOrder(self.date_start, self.date_end)
        Edit_Item_ui.setTabOrder(self.date_end, self.check_hidden)
        Edit_Item_ui.setTabOrder(self.check_hidden, self.check_silenced)
        Edit_Item_ui.setTabOrder(self.check_silenced, self.plain_description)

    def retranslateUi(self, Edit_Item_ui):
        Edit_Item_ui.setWindowTitle(QtGui.QApplication.translate("Edit_Item_ui", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_client.setText(QtGui.QApplication.translate("Edit_Item_ui", "Заказчик", None, QtGui.QApplication.UnicodeUTF8))
        self.label_owner.setText(QtGui.QApplication.translate("Edit_Item_ui", "Владелец", None, QtGui.QApplication.UnicodeUTF8))
        self.label_car_number.setText(QtGui.QApplication.translate("Edit_Item_ui", "РегЗнак", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sts.setText(QtGui.QApplication.translate("Edit_Item_ui", "СТС", None, QtGui.QApplication.UnicodeUTF8))
        self.label_zone.setText(QtGui.QApplication.translate("Edit_Item_ui", "Зона действия", None, QtGui.QApplication.UnicodeUTF8))
        self.box_zone.setItemText(0, QtGui.QApplication.translate("Edit_Item_ui", "СК", None, QtGui.QApplication.UnicodeUTF8))
        self.box_zone.setItemText(1, QtGui.QApplication.translate("Edit_Item_ui", "ТТК", None, QtGui.QApplication.UnicodeUTF8))
        self.box_zone.setItemText(2, QtGui.QApplication.translate("Edit_Item_ui", "МКАД", None, QtGui.QApplication.UnicodeUTF8))
        self.label_status.setText(QtGui.QApplication.translate("Edit_Item_ui", "Статус", None, QtGui.QApplication.UnicodeUTF8))
        self.box_status.setItemText(0, QtGui.QApplication.translate("Edit_Item_ui", "Разовый", None, QtGui.QApplication.UnicodeUTF8))
        self.box_status.setItemText(1, QtGui.QApplication.translate("Edit_Item_ui", "Временный", None, QtGui.QApplication.UnicodeUTF8))
        self.box_status.setItemText(2, QtGui.QApplication.translate("Edit_Item_ui", "Полугодовой", None, QtGui.QApplication.UnicodeUTF8))
        self.box_status.setItemText(3, QtGui.QApplication.translate("Edit_Item_ui", "Годовой", None, QtGui.QApplication.UnicodeUTF8))
        self.label_eco.setText(QtGui.QApplication.translate("Edit_Item_ui", "Эко-класс", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(0, QtGui.QApplication.translate("Edit_Item_ui", "Нет данных", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(1, QtGui.QApplication.translate("Edit_Item_ui", "Не установлен", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(2, QtGui.QApplication.translate("Edit_Item_ui", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(3, QtGui.QApplication.translate("Edit_Item_ui", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(4, QtGui.QApplication.translate("Edit_Item_ui", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(5, QtGui.QApplication.translate("Edit_Item_ui", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(6, QtGui.QApplication.translate("Edit_Item_ui", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(7, QtGui.QApplication.translate("Edit_Item_ui", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.box_eco.setItemText(8, QtGui.QApplication.translate("Edit_Item_ui", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.label_date_start.setText(QtGui.QApplication.translate("Edit_Item_ui", "Дата начала", None, QtGui.QApplication.UnicodeUTF8))
        self.date_start.setDisplayFormat(QtGui.QApplication.translate("Edit_Item_ui", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.date_end.setDisplayFormat(QtGui.QApplication.translate("Edit_Item_ui", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_price.setText(QtGui.QApplication.translate("Edit_Item_ui", "Цена", None, QtGui.QApplication.UnicodeUTF8))
        self.label_payment.setText(QtGui.QApplication.translate("Edit_Item_ui", "Оплата", None, QtGui.QApplication.UnicodeUTF8))
        self.label_description.setText(QtGui.QApplication.translate("Edit_Item_ui", "Примечания", None, QtGui.QApplication.UnicodeUTF8))
        self.check_hidden.setText(QtGui.QApplication.translate("Edit_Item_ui", "Скрытый", None, QtGui.QApplication.UnicodeUTF8))
        self.check_silenced.setText(QtGui.QApplication.translate("Edit_Item_ui", "Напоминание", None, QtGui.QApplication.UnicodeUTF8))
        self.label_date_end.setText(QtGui.QApplication.translate("Edit_Item_ui", "Дата конца", None, QtGui.QApplication.UnicodeUTF8))
        self.label_date_docs.setText(QtGui.QApplication.translate("Edit_Item_ui", "Дата подачи", None, QtGui.QApplication.UnicodeUTF8))
        self.date_docs.setDisplayFormat(QtGui.QApplication.translate("Edit_Item_ui", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))

